spring:
  profiles: dev
  application:
    name: mts-message-tracker

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    healthcheck:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, loggers